#!/bin/bash

: '
 Author: Rocco Pietrofesa
 Date: 9/2/19
 TestMe script
 This script will call the python autograder and pass the second shell argument
 to be evaluated
 
 need to create a version checker for the autograder
'

# text color constants
R='\033[0;31m'    # red
BR='\033[1;31m'   # bold red
G='\033[0;32m'    # green
BG='\033[1;32m'   # bold green
Y='\033[0;33m'    # yellow
BY='\033[1;33m'   # bold yellow
B='\033[0;34m'    # blue
BB='\033[1;34m'   # bold blue
P='\033[0;35m'    # purple
BP='\033[1;35m'   # bold purple
A='\033[0;36m'    # aqua
BA='\033[1;36m'   # bold aqua
X='\033[0m'       # reset

#python3 /bin/check.py $PWD/$1
python3 /bin/testMeFolder/testMe.py $1
