#!/bin/bash

: '
 Author: Rocco Pietrofesa
 Date: 9/2/19
 updateTestMe script
 This script will fetch and overwrite the latest version of the python autograder
 
 need to create a version checker for the autograder
'
echo -e "${Y}Collecting and overwriting testMe Python autograder utility.${X}"

sudo wget -q  wget https://raw.githubusercontent.com/pietrofesar/testMe/master/ch10Solutions.py -O /usr/bin/testMe/ch10Solutions.py
sudo wget -q  wget https://raw.githubusercontent.com/pietrofesar/testMe/master/ch1Solutions.py -O /usr/bin/testMe/chSolutions.py
sudo wget -q  wget https://raw.githubusercontent.com/pietrofesar/testMe/master/ch2Solutions.py -O /usr/bin/testMe/ch2Solutions.py
sudo wget -q  wget https://raw.githubusercontent.com/pietrofesar/testMe/master/ch3Solutions.py -O /usr/bin/testMe/ch3Solutions.py
sudo wget -q  wget https://raw.githubusercontent.com/pietrofesar/testMe/master/ch4Solutions.py -O /usr/bin/testMe/ch4Solutions.py
sudo wget -q  wget https://raw.githubusercontent.com/pietrofesar/testMe/master/ch5Solutions.py -O /usr/bin/testMe/ch5Solutions.py
sudo wget -q  wget https://raw.githubusercontent.com/pietrofesar/testMe/master/ch6Solutions.py -O /usr/bin/testMe/ch6Solutions.py
sudo wget -q  wget https://raw.githubusercontent.com/pietrofesar/testMe/master/ch7Solutions.py -O /usr/bin/testMe/ch7Solutions.py
sudo wget -q  wget https://raw.githubusercontent.com/pietrofesar/testMe/master/ch8Solutions.py -O /usr/bin/testMe/ch8Solutions.py
sudo wget -q  wget https://raw.githubusercontent.com/pietrofesar/testMe/master/helpers.py -O /usr/bin/testMe/helpers.py
sudo wget -q  wget https://raw.githubusercontent.com/pietrofesar/testMe/master/learningPythonsSolutions.py -O /usr/bin/testMe/learningPythonsSolutions.py
sudo wget -q  wget https://raw.githubusercontent.com/pietrofesar/testMe/master/siennaSolutions.py -O /usr/bin/testMe/siennaSolutions.py
sudo wget -q  wget https://raw.githubusercontent.com/pietrofesar/testMe/master/testMe.py -O /usr/bin/testMe/testMe.py

testMe
