#!/bin/bash

: '
 Author: Rocco Pietrofesa
 Date: 9/2/19
 updateTestMe script
 This script will fetch and overwrite the latest version of the python autograder
 
 need to create a version checker for the autograder
'

# text color constants
R='\033[0;31m'    # red
BR='\033[1;31m'   # bold red
G='\033[0;32m'    # green
BG='\033[1;32m'   # bold green
Y='\033[0;33m'    # yellow
BY='\033[1;33m'   # bold yellow
B='\033[0;34m'    # blue
BB='\033[1;34m'   # bold blue
P='\033[0;35m'    # purple
BP='\033[1;35m'   # bold purple
A='\033[0;36m'    # aqua
BA='\033[1;36m'   # bold aqua
X='\033[0m'       # reset
echo -e "${Y}Collecting and overwriting testMe Python autograder utility.${X}"
sudo rm -r /usr/bin/testMeFolder
sudo mkdir /usr/bin/testMeFolder
sudo wget -q  wget https://raw.githubusercontent.com/pietrofesar/testMe/main/ch10Solutions.py -O /usr/bin/testMeFolder/ch10Solutions.py
sudo wget -q  wget https://raw.githubusercontent.com/pietrofesar/testMe/main/ch1Solutions.py -O /usr/bin/testMeFolder/ch1Solutions.py
sudo wget -q  wget https://raw.githubusercontent.com/pietrofesar/testMe/main/ch2Solutions.py -O /usr/bin/testMeFolder/ch2Solutions.py
sudo wget -q  wget https://raw.githubusercontent.com/pietrofesar/testMe/main/ch3Solutions.py -O /usr/bin/testMeFolder/ch3Solutions.py
sudo wget -q  wget https://raw.githubusercontent.com/pietrofesar/testMe/main/ch4Solutions.py -O /usr/bin/testMeFolder/ch4Solutions.py
sudo wget -q  wget https://raw.githubusercontent.com/pietrofesar/testMe/main/ch5Solutions.py -O /usr/bin/testMeFolder/ch5Solutions.py
sudo wget -q  wget https://raw.githubusercontent.com/pietrofesar/testMe/main/ch6Solutions.py -O /usr/bin/testMeFolder/ch6Solutions.py
sudo wget -q  wget https://raw.githubusercontent.com/pietrofesar/testMe/main/ch7Solutions.py -O /usr/bin/testMeFolder/ch7Solutions.py
sudo wget -q  wget https://raw.githubusercontent.com/pietrofesar/testMe/main/ch8Solutions.py -O /usr/bin/testMeFolder/ch8Solutions.py
sudo wget -q  wget https://raw.githubusercontent.com/pietrofesar/testMe/main/helpers.py -O /usr/bin/testMeFolder/helpers.py
sudo wget -q  wget https://raw.githubusercontent.com/pietrofesar/testMe/main/learningPythonSolutions.py -O /usr/bin/testMeFolder/learningPythonSolutions.py
sudo wget -q  wget https://raw.githubusercontent.com/pietrofesar/testMe/main/siennaSolutions.py -O /usr/bin/testMeFolder/siennaSolutions.py
sudo wget -q  wget https://raw.githubusercontent.com/pietrofesar/testMe/main/testMe.py -O /usr/bin/testMeFolder/testMe.py

sudo rm /usr/bin/updateTestMe 
sudo wget -q  wget https://raw.githubusercontent.com/pietrofesar/testMe/main/updateTestMe -O /usr/bin/updateTestMe; sudo chmod +x /usr/bin/updateTestMe

testMe
